// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Recipe struct {
	RecipeID            int32
	RecipeBookID        int32
	Name                string
	CookingInstructions string
	Ingredients         string
	Likes               pgtype.Int4
	CreatedAt           pgtype.Timestamptz
}

type RecipeBook struct {
	RecipeBookID int32
	UserID       int32
	Name         string
	Description  pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	UserID       int32
	Username     string
	PasswordHash []byte
	Email        string
	CreatedAt    pgtype.Timestamptz
}
